trigger:
  branches:
    include:
      - main

jobs:
- job: BuildAndPublish
  displayName: 'Build and Publish'
  pool:
    vmImage: 'ubuntu-latest'

  steps:
  - checkout: self

  - task: MavenAuthenticate@0
    inputs:
      mavenCredentials: 'MavenCredentials'

  - task: Maven@3
    inputs:
      mavenPomFile: 'pom.xml'
      goals: 'clean package'
      options: '-DskipTests'

  - task: SonarQubePrepare@4
    inputs:
      SonarQube: 'Sonar'  # Replace with the name of your SonarQube service connection
      scannerMode: 'CLI'
      configMode: 'file'
      cliProjectKey: 'qt-devops'
      cliProjectName: 'Qt@devops'
      cliSources: 'src'

  - task: SonarQubeAnalyze@4

  - script: mvn verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=qt-devops_qtdevops

  - task: Docker@2
    displayName: 'Build Docker image'
    inputs:
      command: 'build'
      containerRegistry: 'Docker-Hub-Connection'
      repository: 'shivakrishna99/az-petclinic'
      dockerfile: '**/Dockerfile'
      buildContext: '$(Build.SourcesDirectory)'
      tags: |
        latest
        $(Build.BuildId)

  - task: Docker@2
    displayName: 'Push Docker image'
    inputs:
      command: 'push'
      containerRegistry: 'Docker-Hub-Connection'
      repository: 'shivakrishna99/az-petclinic'
      tags: |
        latest
        $(Build.BuildId)

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifacts'
    inputs:
      PathtoPublish: '$(Build.SourcesDirectory)/target'
      ArtifactName: 'Petclinic'
